version: "3"
services:
    data-provider:
        image: baelfire/data-provider:latest
        ports:
            - "80:5000"
        volumes:
            - .:/app
        command:
            - source venv\bin\activate
            - python app.py
        working_dir: /app
        restart: unless-stopped