version: "3"
services:
    data-provider:
        build: .
        ports:
            - "80:5000"
        volumes:
            - .:/app
        command:
            - python
            - app.py
        working_dir: /app
        restart: unless-stopped