version: "3"
services:
    data-provider:
        image: baelfire/data-provider:latest
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        command:
            - python3
            - app.py
        working_dir: /app
        restart: unless-stopped